language: rust

rust:
  - stable
  - nightly
env:
  - FEATURES=''
  - FEATURES='unsafe_internals'

before_script:
  - "[ \"$TRAVIS_RUST_VERSION\" == 'nightly' ] || rustup component add rustfmt-preview"

script:
  - cargo build --tests --features "$FEATURES"
  - cargo test --features "$FEATURES"
  - "[ \"$TRAVIS_RUST_VERSION\" != 'nightly' ] || cargo bench --features \"$FEATURES\""
  - "[ \"$TRAVIS_RUST_VERSION\" == 'nightly' ] || cargo fmt --all -- --check"

cache: cargo
