language: rust

rust:
  - stable
  - nightly
env:
  - FEATURES=''
  - FEATURES='unsafe_internals'

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo build --tests --features "$FEATURES"
  - cargo test --features "$FEATURES"
  - "[ \"$TRAVIS_RUST_VERSION\" != 'nightly' ] ||  cargo bench --features \"$FEATURES\""
  - "[ \"$TRAVIS_RUST_VERSION\" != 'nightly' ] ||  cargo fmt -- --check"

cache: cargo
